import React from 'react';

import { Heading, Block } from 'sly/web/components/atoms';


const PPHTML = () => {
  return (
    <Block>

      <Heading level="title">SENIORLY PRIVACY POLICY</Heading>
      <Heading level="subtitle">UPDATED APRIL 8, 2019</Heading>
      <p>We appreciate your use of our website and services (“Site” and “Services”). At Seniorly, we respect your privacy and are committed to protecting your personal information.</p>
      <p>We encourage you to read this policy to understand the information we collect and how we use it. This privacy policy explains the collection, use, and disclosure practices of this Web site. We may update this statement occasionally, and we encourage you to check the date of our privacy policy whenever you visit the Site to see whether it has been modified since your last visit.</p>
      <p>We do not sell your name, email address or other information, except to third parties which may provide or offer the services you've requested from us or as otherwise described below under Disclosure of Personal Information.</p>
      <Heading level="subtitle">COLLECTION OF PERSONAL INFORMATION</Heading>
      <p>For services provided on or in connection with our Website, we may ask you to provide personal information such as name, email address, phone number and zip code, and personally identifiable information, and may or may not include any other information provided by or for you, and/or provided by any other person for whom you may be seeking senior housing and/or care services ("Personal Information"). We may collect and store any Personal Information.</p>
      <p>In addition we and our partners use various technologies to collect information automatically when you access and use the Services, including cookies, web beacons and other similar technologies. Cookies are bits of electronic information that can be transferred to your computer or other electronic device to uniquely identify your browser. When you use the Services, we and our partners may place one or more cookies on your computer or other electronic device or use other technologies that provide similar functionality. We and our partners may use cookies to connect your activity on the Services with other information we store about you in your account profile or your prior interactions on the Services to, for example, store your preferences. The use of cookies helps us improve the quality of the Services to you, by identifying information which is most interesting to you, tracking trends, measuring the effectiveness of advertising, or storing information you may want to retrieve on a regular basis, such as your favorite homes. At any time, you may adjust settings on your browser to refuse cookies according to the instructions related to your browser. However, if you choose to disable cookies, many of the free features of the Services will not operate properly.</p>
      <p>The pages on the Services may also include web beacons or pixels, which are electronic files to count users who have visited that page, to track activity over time and across different websites, to determine users’ interactions with emails we send, to identify certain cookies on the computer or other electronic device accessing that page, or to collect other related information, and this information may be associated with your unique browser, device identifier, or Internet Protocol address. We may, for example, implement a pixel on the pages of the Services where you view a certain advertisement so that we can track whether you visit a website associated with that advertisement at a later time.</p>
      <p>Please be advised that the practices described in this Privacy Policy apply to information gathered online at our Web site, and to information that you may submit to us offline; to Websites maintained by other companies, or organizations to which we may link; and to Personal Information we may collect further from third parties.</p>
      <p>Mobile device and mobile browser information. You may adjust settings on your mobile device and mobile browser regarding cookies and sharing of certain information, such as your mobile device model or the language your mobile device uses, by adjusting the privacy and security settings on your mobile device. Please refer to the instructions provided by your mobile service provider or mobile device manufacturer.</p>
      <p>Location Data. If you enable location services on your mobile device, Seniorly may collect the location of your device, which we use to provide you with location-based information and advertising. If you wish to deactivate this feature, you can disable location services on your mobile device.</p>
      <p>Usage logs. We collect information about your use of our Services, including the type of browser you use, access times, pages viewed, your IP address and the page you visited before navigating to our Services. We also collect information about the computer or mobile device you use to access our Services, such as the hardware model, operating system and version, unique device identifiers, mobile network information, and browsing behavior.</p>
      <p>Calls and text messages. Calls between you and Seniorly, or between you and third parties made through Seniorly (such as Partner Agents you contact about a property through a form or link on our website, or using contact information found on our website), may be recorded or monitored for quality assurance and customer service purposes. You will be notified at the beginning of a call if it may be recorded or monitored. Seniorly may use a third-party service provider to track phone calls and text messages between you and real estate professionals so that we and the partner agents can access certain details about the contact. As part of this process, Seniorly and its service provider will receive in real time and store data about your call or text message, including the date and time of the call or text message, your phone number, and the content of the text message.</p>
      <p>Public content. You may provide information publicly through the Services, such as when you leave a review for a Partner Agent or Community, or when you contribute to discussion forums.</p>
      <p>Social networks. If you use the social networking connection functions offered through the Services, we may access all of your social network profile information that you have made available to be shared and to use it in accordance with this privacy policy. Please refer to the instructions governing your social network account to manage the information that is shared through your account.</p>
      <Heading level="subtitle">USE OF PERSONAL INFORMATION</Heading>
      <p>We use Personal Information to provide you with the services you have requested from us and to provide services to the senior housing and care providers who have contracted with us ("Participating Partners") and our Partner Agents (“Partner Agent”) to be part of our referral information service program in relation to the services that we provide you. In addition, we use Personal Information to send you periodic email and newsletter communications about products and services offered by us or third parties, to operate and improve our Web site and services, to respond to customer inquiries, and to send you survey or other communications.</p>
      <p>We use Personal Information also for our own internal business purposes including statistical, design or operational purposes, such as to estimate our audience size, measure aggregate traffic patterns and understand demographic trends among our users.</p>
      <p>We also use Personal Information to process payments if you have selected one of our Fee or Subscription Services.</p>
      <Heading level="subtitle">DISCLOSURE OF PERSONAL INFORMATION</Heading>
      <p>We may disclose, sell or share Personal Information about you with other people including:</p>
      <ul>
        <li>Participating Partners and Partner Agents. We may disclose, sell or share Personal Information to one or more Participating Partners in order to provide you with the services you’ve requested. The Participating Partners may contact you directly by email, telephone, regular mail, in person visits or other means. We do not control how these Participating Partners use or disclose your Personal Information.</li>
        <li>Other Third Party Providers. We may disclose, sell or share Personal Information to one or more third parties with whom we have contracted to provide services to us. We may also disclose Personal Information to one or more third parties who are interested in providing services or products to you. We do not control how these third parties use or disclose your Personal Information.</li>
        <li>Internal Analysis and Operations. We may disclose Personal Information for our own internal statistical, design or operational purposes, such as to estimate our audience size, measure aggregate traffic patterns, and understand demographic trends among our users. We may outsource these tasks and disclose Personal Information about you to third parties, provided the use and disclosure of your Personal Information by these third parties is restricted to performance of such tasks and subject to confidentiality.</li>
        <li>Legal and Other Compliance. We may disclose Personal Information when we believe it is appropriate to comply with the law; to enforce or apply this Privacy Policy or our other policies or agreements; to protect our or our users' rights, property or safety; to protect our users from fraudulent, abusive or unlawful use of, our site; or if we reasonably believe that an emergency involving immediate danger of death or serious physical injury to any person requires disclosure of communications or justifies disclosure of records without delay.</li>
        <li>Business Transfers. We may disclose Personal Information as part of any merger, acquisition, debt financing, sale of company assets or other business transaction.</li>
        <li>Aggregated Information: We may share aggregated, anonymous information that includes or is based on information about you with third parties. This is information that is combined with the information of other users and does not directly identify you. Depending on the circumstances, we may or may not charge third parties for this aggregated information. We also may not limit the third parties’ use of the aggregated information.</li>
      </ul>
      <Heading level="subtitle">USE OF NON-PERSONAL INFORMATION</Heading>
      <p>Non-personal information collected at the Site may be used and disclosed to improve the performance, functionality and content of the Site. For example, we may collect and analyze collected aggregate information to determine how many visitors arrived at certain pages of the Site, how long they stayed on those pages, and where they went afterwards. This information allows us to determine which pages might be the most interesting to our users and enables us to provide you with a richer experience on the Site. Additionally, we may use non-personal information to improve the performance of the Site and to customize the content, features and layout of the Site pages for you.</p>
      <p>Occasionally we share aggregate information with third parties, such as our advertisers and business partners, for marketing and promotional purposes</p>
      <p>We may supplement aggregate information collected from the Site with similar information obtained from companies with whom we have marketing or other business relationships and other third party sources. If aggregate information is ever linked with your Personal Information, such information will be treated as Personal Information for the purposes of this Privacy Policy as long as it is linked.</p>
      <Heading level="subtitle">LINKS TO THIRD PARTIES</Heading>
      <p>Please be advised that we may provide links to third party Websites from our Site as a service to our users, but we have no ability to control, and are not responsible for, the privacy and data collection, use, and disclosure practices of such sites and the privacy policies of such Websites may differ from the Site. Therefore, we encourage you to review and understand the privacy policies of such Websites before providing them with any information. These other Websites may send their own cookies to you, collect your data or solicit your Personal Information. Always be aware of where you end up. You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to accept cookies, you also have the ability to later delete cookies that you have accepted.</p>
      <Heading level="subtitle">THIRD PARTY ADVERTISING COMPANIES</Heading>
      <p>Third party advertisers or ad networks may use cookies or other technologies on our Site for various purposes, including measuring the effectiveness of their ads and analyzing and personalizing ads or other content delivered to you. We have no ability to control the privacy and data collection, use, and disclosure practices of such Websites and the privacy policies of such Websites may differ from the Site. Therefore, we encourage you to review and understand the privacy policies of such Websites before providing them with any information.</p>
      <Heading level="subtitle">CHILDREN</Heading>
      <p>We do not intend, and this Site is not designed, to collect Personal Information from children under the age of 13. If you are under 13 years old, you should not register for our services or otherwise provide information on our Site.</p>
      <Heading level="subtitle">DO NOT TRACK DISCLOSURES</Heading>
      <p>No action is taken in response to web browser "do not track" signals or other mechanisms that provide consumers the ability to exercise choice regarding the collection of personally identifiable information about an individual consumer’s online activities over time and across third-party websites or online services. Although we use Google Analytics and other third party tracking tools for our Site, we are not aware if third parties collect personally identifiable information about an individual consumer’s online activities when a consumer uses our Site.</p>
      <Heading level="subtitle">YOUR CONSENT</Heading>
      <p>By using our Site, you consent to the terms of our Privacy Policy and to our collection, use, and disclosure of Personal Information for the purposes given above.</p>
      <Heading level="subtitle">OPT-OUT OF SENIORLY COMMUNICATIONS</Heading>
      <p>We may periodically send you newsletters and other communications that promote the use of our services. When you receive our newsletters, you may indicate a preference to stop receiving further newsletters by following the opt-out instructions that we include in the newsletter we send you. However, if you wish to opt-out of communications with Participating Partners, you must contact them directly as we do not control communications from Participating Partners.</p>
      <Heading level="subtitle">SECURITY AND RETENTION OF INFORMATION</Heading>
      <p>Seniorly takes reasonable steps to protect the information users share with us from unauthorized use, access, and disclosure, both during transmission and at rest. However, no transmission of information via the Internet nor electronic storage solution can be entirely secure, so please be aware that we cannot guarantee absolute security.</p>
      <p>We will retain your information for as long as necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted by law.</p>
      <Heading level="subtitle">TRANSFER OF INFORMATION TO UNITED STATES</Heading>
      <p>Seniorly is based in the United States and you acknowledge that the information we collect is governed by U.S. law. By accessing or using the Services or otherwise providing information to us, you consent to the processing, transfer, and storage of information in and to the United States, where you may not have the same rights and protections as you do under local law.</p>
      <Heading level="subtitle">YOUR CALIFORNIA PRIVACY RIGHTS</Heading>
      <p>Companies that collect personally identifiable information from California residents and disclose such information to third parties for marketing purposes must, in response to a request by a consumer, either (1) provide a list detailing the categories of information shared and the entities to which such information was provided, or (2) provide a mechanism by which a consumer may opt-out of having their information shared with third parties. We have elected the second option and you may request that your personally identifiable information not be shared with third parties by sending your request, including your full name, email address and postal address to: Seniorly, Inc. Attn: Legal, P.O. Box 26804 San Francisco, CA 94126.</p>
      <p>In accordance with California Civil Code Sec. 1789.3, California resident users are entitled to know that they may file grievances and complaints with California Department of Consumer Affairs, 400 R Street, Suite 1080, Sacramento, CA 95814; or by phone at 916-445-1254 or 800-952-5210; or by email to dca@dca.ca.gov</p>
      <Heading level="subtitle">CONTACTING SENIORLY</Heading>
      <p>If you have any questions about this Privacy Policy or the privacy practices of our Site, please contact us at privacy@seniorly.com</p>
      <Heading level="subtitle">CHANGES TO POLICY</Heading>
      <p>Please note that this policy may be amended from time to time. You should check back for the most current version before relying on any of the provisions in this privacy policy. We will provide notice of material changes to the policy, either by posting a notice on our websites, by sending an email, or some other reasonable method.</p>
    </Block>
  );
};

export default PPHTML;
