export const TEST_COMMUNITY = 'eskaton-village-placerville';
export const PROFILE_TEST_COMMUNITY = 'julie-s-care-home';
export const BUENA_VISTA_COMMUNITY = 'buena-vista-manor-house';

export const ServicesAmenitiesFilters = {
  careServices: [
    'activities of daily living assistance',
    'assistance with dressing',
    'medication management',
    'transportation arrangement (medical)',
    'coordination with health care providers',
    '24-hour supervision',
    'special dietary restrictions',
    'diabetes care',
    '24-hour nursing',
    "parkinson's care",
    'rehabilitation program',
    'mild cognitive impairment',
    'specialized memory care programming',
    'hospice waiver',
    'same day assessments',
    'assistance with bathing',
    'assistance with transfers',
    'meal preparation and service',
    'transportation to doctors appointment',
    '24-hour call system',
    'physical therapy',
    'diabetes diet',
    'administer insulin injections',
    '12-16 hour nursing',
    'care with behavioral issues',
    'mental wellness program',
    'dementia waiver',
    'respite program',
    'accept incoming residents on hospice',
    'preventative health screenings',
  ],
  personalSpace: [
    'cable',
    'internet',
    'private bathrooms',
    'kitchenettes',
    'wifi',
    'telephone',
    'air-conditioning',
    'air conditioning',
    'fully furnished',
  ],
  communitySpace: [
    'dining room',
    'family private dining rooms',
    'organic food and ingredients',
    'outdoor space',
    'garden',
    'gaming room',
    'fitness room',
    'spa',
    'wellness center',
    'located close to shopping centers',
    'pet friendly',
    'restaurant-style dining',
    'cafe',
    'on-site market',
    'outdoor patio',
    'small library',
    'computer center',
    'swimming pool',
    'beauty salon',
    'religious/meditation center',
    'located close to restaurants',
  ],
  nonCareServices: [
    'housekeeping and linen services',
    'community operated transportation',
    'concierge services',
    'community-sponsored activities',
    'planned day trips',
    'continuing learning programs',
    'transportation arrangement (non-medical)',
    'fitness programs',
    'scheduled daily activities',
    'resident-run activities',
    'move-in coordination',
    'family education and support services',
  ],
};

