import React from 'react';

import { Heading, Block } from 'sly/components/atoms';


const TOSHTML = () => {
  return (<Block>
    <Heading level="subtitle">SENIORLY TERMS OF USE</Heading>
    <h3>UPDATED APRIL 2019</h3>
    <p>Hello and thank you for your interest in Seniorly. By registering or creating a new account , or otherwise using Seniorly (“Site”), its Partner Agent network (“Partner Agents”), or services (“Services”) provided by Seniorly or its partners, or accessing any content provided by Seniorly through its Services, you agree to the following terms of use, as updated from time to time (“Terms of Use”). Please read these terms carefully. If you do not agree to these Terms of Use, please do not use the Site, Partner Agents, or Services.</p>
    <p>We reserve the right to change or modify any of the Terms of Use, the Site, Partner Agents, and/or Services at any time. If we decide to change our Terms of Use, we will post a new version on the Site and update the date. Any changes or modifications will be effective immediately upon posting of the revisions on the Site, regardless of whether we provide you with any specific notice of such changes. Your use of the Site and/or the Services following the posting of changes or modifications to the Terms of Use will constitute your acceptance of the revised Terms of Use. If you do not agree to the amended terms, you should immediately stop using the Site and/or Services.
    </p>
    <p>
      The Terms of Use do not alter in any way the terms or conditions of any other agreement you may have with Seniorly for services, products, or otherwise. Your access to, and use of, the Site may also be subject to any legal notices or additional terms and conditions applicable to the Site and/or Services, in addition to these Terms of Use, ("Additional Terms"). Where Additional Terms apply to the Services, the Additional Terms will be accessible for you to read through your use of the Services and/or provided separately. These Terms of Use, together with the Additional Terms, form a legally binding agreement between you and Seniorly in relation to your use of the Site and/or Services. If there is any contradiction between what the Additional Terms say and what these Terms of Use say with respect to the Services, then the Additional Terms shall take precedence in relation to that Service.
    </p>
    <p>You must be at least 18 years of age to use the Service. By agreeing to these Terms of Use, you represent and warrant that: (a) you are at least 18 years of age; (b) you have not previously been suspended or removed from the Services; and (c) your registration and your use of the Services is in compliance with all applicable laws and regulations. To access some features of the Services, you may be required to register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as email address or other contact information. You agree that the information you provide is accurate and that you will keep it accurate and up-to-date at all times. When you register, you may be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password, and you are responsible for all actions taken via your account. You may not share your user account(s) with others. Unless you have entered into a commercial agreement with Seniorly permitting you to use the Services for transactions on behalf of another person, you may only use the Services for transactions on your own behalf, and not on behalf of any other person.
    </p>
    <Heading level="subtitle">OUR SERVICES</Heading>
    <p>Seniorly is a senior living information portal that lists senior living and care services. Seniorly also provides software to local placement agents and senior housing communities including an online payments solution for paying for rent and services. Seniorly works with independent living, residential care homes, assisted living, memory care and skilled nursing facilities (“Participating Communities”). Seniorly also works with local placement agents and geriatric care managers to assist families in person or over the phone (“Partner Agents”). Based on the family's stated needs and preferences, we provide the family with information about contracted communities and we forward the family's information to those Participating Communities or Partner Agents. Families can review detailed information about local and national Participating Communities, and get personalized, knowledgeable assistance by telephone or in-person from a local Partner Agent. The service is offered at no charge to families as the Participating Communities pay a fee to Seniorly or its Partner Agents.</p>
    <Heading level="subtitle">PARTICIPATING COMMUNITIES</Heading>
    <p>The Participating Communities are solely responsible for evaluating, accepting (or declining, as appropriate), and caring for all residents, including, without limitation, ensuring that their staff are appropriately qualified, current on education, and possess the necessary facilities, resources, and equipment to competently provide the services and care required by its residents whether referred from Seniorly or a Partner Agent. Each Participating Community is responsible for the conditions at its community and the training of and acts and omissions of its employees, contractors, vendors, and any other individual who works at or for a community.</p>
    <p>We do not ensure the accuracy of any of the information posted by and/or for the Participating Community on the Site, and do not take any responsibility or assume any liability for any actions you may take as a result of reading the information posted by and/or for the Participating Community on the Site. By using the Site and/or Services, you assume all associated risks.
    </p>
    <Heading level="subtitle">NO ENDORSEMENT; NO AFFILIATION; NOT A BROKER</Heading>
    <p>We, and Partner Agent, exercise no independent judgment as to the quality of, nor do we recommend or endorse, any Participating Community. We provide only an information service and do not (1) place the consumer in any Participating Community, (2) perform any medical assessment of or for the consumer or the Participating Community, or (3) participate in the consumer's and Participating Community's decision regarding final selection or admittance. Further, we are not a representative of or agent for either the consumer or the Participating Community and do not act on either's behalf. It is the responsibility solely of the Participating Community and the potential resident, and/or the potential resident's family and care provider(s) and/or other involved parties acting on the potential resident's behalf to determine if any person is an appropriate admission to the Participating Community.</p>
    <Heading level="subtitle">NO PROFESSIONAL ADVICE</Heading>
    <p>All information, materials, content and/or advice on the Site or provided through the Services is for informational purposes only and is not intended to replace or substitute for any professional, financial, medical, legal or other advice. Seniorly expressly disclaims, and you expressly release Seniorly from, any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Site and/or Services. You should consult with an appropriately trained specialist for all concerns that require medical, legal, financial or other professional advice.</p>
    <Heading level="subtitle">FEES</Heading>
    <p>1. Generally. You may be required to pay fees to access certain features of the Services. All fees are in U.S. dollars and are non-refundable. If Seniorly changes the fees for all or part of the Services, including by adding fees or charges, Seniorly will provide you advance notice of those changes. If you do not accept the changes, Seniorly may discontinue providing the applicable part of the Services to you. Seniorly’s authorized third-party payment processor will charge the payment method you specified at the time of purchase. You authorize Seniorly to charge all fees as described in these Terms of Use for the Services you select to that payment method. If you pay any fees with a credit card, Seniorly may seek pre-authorization of your credit card account before your purchase to verify that the credit card is valid and has the necessary funds or credit available to cover your purchase.
    </p>
    <p>2. Subscriptions. The Services may include features that allow for automatically recurring payments for periodic charges (“Subscription Service”). If you decide to activate a Subscription Service, you authorize Seniorly to periodically charge, on a going-forward basis and until cancellation of either the recurring payments or your account, all accrued sums on or before the payment due date for the accrued sums. The subscription will continue unless and until you cancel your subscription, or we terminate it. You must cancel your subscription before it renews in order to avoid billing of the next periodic subscription fee to your account. We will bill the periodic subscription fee to the payment method you provide to us during registration (or to a different payment method if you change your payment information). Seniorly may change the subscription fee for any subsequent subscription period but will provide you advance notice of any increase before it applies.</p>
    <Heading level="subtitle">USER MATERIALS</Heading>
    <p>1. UGC Definition; License Grant. Certain portions of the Services may allow users to upload or otherwise provide to Seniorly images, photos, video, data, text, listings, and other content (“User Materials”). By uploading or otherwise providing User Materials to the Services, you grant Seniorly an irrevocable, perpetual, royalty-free worldwide license to: (i) use, copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, modify, prepare derivative works of or incorporate into other works, and translate your User Materials, in connection with the Services, or in any other media; and (ii) sublicense these rights, to the maximum extent permitted by applicable law. Seniorly will not pay you for your User Materials or to exercise any rights related to your User Materials set forth in the preceding sentence. Seniorly may remove or modify your User Materials at any time. You are solely responsible for all User Materials made through your user account(s) on the Services or that you otherwise make available through the Services. For all User Materials, you represent and warrant that you are the creator and owner of the User Materials, or have the necessary licenses, rights, consents, and permissions (including all permissions required under applicable privacy and intellectual property law) to authorize Seniorly and other users to access and use your User Materials as necessary to exercise the licenses granted by you under these Terms of Use.</p>
    <p>2. UGC Disclaimer. Seniorly is under no obligation to edit or control your User Materials or the User Materials of any other User and will not be in any way responsible or liable for any User Materials. Seniorly may, however, at any time and without prior notice, screen, remove, edit, or block any User Materials on the Services, including User Materials, that in Seniorly’s sole judgment violate these Terms of Use or are otherwise objectionable, including in any way described in our privacy policy. You understand that when using the Services, you may be exposed to User Materials of other users and acknowledge that User Materials may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you may have against Seniorly with respect to User Materials. Seniorly expressly disclaims any and all liability in connection with User Materials. If notified by a user or content owner that User Materials allegedly do not conform with these Terms of Use, Seniorly may investigate the allegation and determine in Seniorly’s sole discretion whether to remove the User Materials, which Seniorly reserves the right to do at any time and without notice. </p>
    <Heading level="subtitle">PRIVACY AND CONSENT TO COMMUNICATIONS</Heading>
    <p>Your privacy is important to us, and we provide a Privacy Policy that sets out how we collect and use your personal information collected from the Site. Please review our Privacy Policy to which you should refer to fully understand how we collect and use personal information; your use of the Site and/or Services will constitute your acceptance of the terms and conditions of the Privacy Policy. By filling out any forms on the Site or providing information to us, you expressly consent to being contacted by us and/or the Participating Communities, whether by phone, mobile phone, email, mail or otherwise. If you are a customer or potential customer of the Services, you authorize us to provide the information that you provided us and related information we may receive from third parties to Participating Communities for the purpose of providing Services. Such authorization shall continue in effect until you have withdrawn your consent by requesting that we no longer provide you Services; provided that we may continue to refer to and/or disclose your information when communicating with a Participating Community as necessary for our normal Participating Community related business practices (such as Participating Community billing matters) until such matters are closed.</p>
    <Heading level="subtitle">RECORDED TELEPHONE COMMUNICATIONS</Heading>
    <p>Telephone communications between You and Seniorly may be recorded or monitored for quality control purposes. By filling out any forms on the Sites or by providing information to us, you expressly consent to the recording of these telephone communications.</p>
    <Heading level="subtitle">USE OF SITES; LIMITED LICENSE</Heading>
    <p>You are granted a limited, non-sublicensable license to access and use the Site and all content, data, information and materials included in the Site (the "Site Materials") solely for your personal use, subject to the terms and conditions set forth in the Terms of Use. You will not use the Site or any of the Site Materials other than for their intended purpose or in any way that is unlawful or harms Seniorly. Any use of the Site or the Site Materials other than as specifically authorized herein is strictly prohibited and, without limiting other available remedies, will automatically and immediately terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in the Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable by Seniorly at any time.
    </p>
    <Heading level="subtitle">PROHIBITED USE</Heading>
    <p>The following are examples of some actions and activities that are prohibited by you in accessing and/or using the Sites and/or Services, and you agree not to do any of the following:</p>
    <ul>
      <li >Using the Sites for commercial purposes.</li>
      <li >Conducting or promoting any illegal activities while using the Sites or Services.</li>
      <li >Uploading or attempting to upload or otherwise transferring any virus, worm, trap door, back door, Trojan horse, timer, clock, counter, or other limiting or malicious routine, instruction, or design that would cause harm to the Sites, Seniorly's computer and/or telecommunication systems or data.</li>
      <li >Interfering in any way with the proper functioning of the Sites (including harming, disabling, or significantly slowing) or interfering with or disrupting any servers or networks connected to the Sites, or disobeying any requirements, procedures, policies or regulations of networks connected to the Sites.</li>
      <li >Modifying, copying, distributing, reselling, transmitting, displaying, performing, reproducing, publishing, licensing, creating derivative works from, framing in another web page, and/or using on any other Web site or service any of the Sites content.</li>
      <li >Engaging in the practices of "screen scraping," "database scraping," "data mining" or any other activity with the purpose of obtaining lists of users or other information, in whole or in part, from the Sites or use web "bots" or similar data gathering or extraction methods for such purposes.</li>
      <li >Attempting to reverse engineer or jeopardize the correct functioning of the Sites, or otherwise attempting to derive the source code of the software (including the tools, methods, processes, and infrastructure) that enables or underlies the Sites;</li>
      <li >Attempting to gain access to secured portions of the Sites.</li>
      <li >Circumventing, attempting to circumvent, disabling, or attempting to disable, or discovering or attempting to discover any security measures (including without limitation encryption algorithms, keys, passwords, and the like) used by or for Seniorly to protect its computer and/or telecommunications systems.</li>
      <li >Using the Sites and/or Services to generate unsolicited email advertisements or spam; and/or allowing, enabling, or otherwise supporting the transmission of mass unsolicited, commercial advertising or solicitations via e-mail (spam).</li>
      <li >Using the Sites and/or Services to stalk, harass or harm another individual.</li>
      <li >Impersonating any person or entity, or otherwise misrepresenting your affiliation with a person or entity; or</li>
      <li >Uploading, distributing or printing anything that may be harmful to minors.</li>
      <li >Mirroring or framing the Sites, placing pop-up windows over its pages, or otherwise affecting the display of its pages.</li>
      <li >Engaging in any other action in any way that is unlawful or harms Seniorly.</li>
    </ul>
    <Heading level="subtitle">INTELLECTUAL PROPERTY OWNERSHIP</Heading>
    <p>All trademarks, service marks, and trade names are proprietary to Seniorly and our licensors. All rights, title, and interests in and to the Site, including content, materials, trademarks and other intellectual property contained in the Site, vest solely in Seniorly and its licensors. The Seniorly name, and any Seniorly products and services, slogans or logos referenced herein on the Site are either trademarks or registered trademarks of Seniorly in the United States and/or other countries. The names of actual third party companies and products mentioned in the Site may be the trademarks of their respective owners. Any rights not expressly granted herein are reserved.</p>
    <Heading level="subtitle">ACCOUNT SECURITY</Heading>
    <p>On certain portions of the Site, you will be provided with a password and user identification to use the Site. You must agree to abide by these Site Terms and are responsible for all activity under such user identification. You are responsible for maintaining the confidentiality and security of any password connected with your account.</p>
    <Heading level="subtitle">THIRD PARTY & LINKED SERVICES</Heading>
    <p>The Services include links to third-party products, services and Web sites, as well as materials provided by third parties, and may include functionality that allows for the distribution of your User Materials or your personal information (collectively, your “User Information”) to third parties not under Seniorly’s control (each, a “Third-Party Provider”). The Site may a;sp provide links to external Websites ("External WebSites"). We provide these links to External Websites for your convenience only. We do not control such External Websites; therefore, Seniorly is not responsible for the content of any linked site or any link contained in a linked site. Our inclusion of links to such External Websites does not imply any endorsement of any such third party who advertises their goods or services through the Site (including Participating Communities and Partner Agents). We make no claim or representation regarding, and accept no responsibility
      for, the quality, content, nature or reliability of External Websites.
    </p>
    <p>Third-Party Providers are solely responsible for their services. You are responsible for your use and submission of User Information to any third-party, and your dealings or business conducted with any third party arising in connection with the Services are solely between you and such third party. Your use of third-party sites, services, or products may be subject to associated third-party terms of use and privacy policies or other agreements, which you are solely responsible for complying with. Seniorly does not endorse, and takes no responsibility for such products, services, Web sites, and materials, or a Third-Party Provider’s use of your User Information. By using a tool that allows for User Information to be transferred, you agree that Seniorly may transfer the applicable User Information or other information to the applicable third-parties, which are not under the control of Seniorly. If you submit a contact form or otherwise indicate your interest in contacting a Third-Party Provider, you may receive telemarketing calls from the Third-Party Provider using the contact information you provided. Third-Party Providers may keep your contact information and any other information received by the Third-Party Provider in processing a contact or other request form. Seniorly is not responsible for any damages or costs of any type arising out of or in any way connected with your dealings with these third parties.</p>
    <p>Additional Terms for Third Party Services. Certain aspects of the Services include third-party tools that are subject to additional third-party terms, including, but not limited to, the following:</p>
    <p>Google Maps. Some of the Services implement the Google Maps web mapping service. Your use of Google Maps is subject to Google's terms of use, available at http://www.google.com/intl/en_us/help/terms_maps.html, and Google’s Privacy Policy, available at https://www.google.com/intl/ALL/policies/privacy/index.html.</p>
    <p>Stripe. Some of the Services allow you to use Stripe Connect to make payments to other users, and may include additional processing or application fees detailed when you choose to connect to Stripe. Your use of Stripe is subject to the Stripe Connected Account Agreement, available at https://stripe.com/us/connect-account/legal. Additionally, by using Stripe, you agree not to use Stripe (and the Services generally) for any Prohibited Business purposes, as listed at https://stripe.com/us/prohibited-businesses.
    </p>
    <p>Plaid. The rental payments feature allows you to link your bank account through Plaid for the purposes of making or receiving rental payments. By using Plaid, you agree to your personal and financial information being transferred, stored, and processed by Plaid in accordance with the Plaid Privacy Policy, available at https://plaid.com/legal.</p>
    <Heading level="subtitle">COPYRIGHT INFRINGEMENT NOTICES &amp; DMCA NOTICES</Heading>
    <p>If you believe in good faith that materials hosted by us infringe your copyright, you (or your agent) may send us a written notice that includes the following information. Please note that we will not process your complaint if it is not properly filled out or is incomplete. Any misrepresentations in your notice whether content or activity is infringing may expose you to liability for damages.</p>
    <ol>
      <li >A clear identification of the copyrighted work you claim was infringed</li>
      <li >A clear identification of the material you claim is infringing on the Website, such as a link to the infringing material.</li>
      <li >Your address, email address and telephone number.</li>
      <li >A statement that you have a ''good faith belief that the material that is claimed as copyright infringement is not authorized by the copyright owner, its agent, or the law.''</li>
      <li >A statement that ''the information in the notification is accurate, and under penalty of perjury, the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed''</li>
      <li >A signature by the person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
      <li >You may send your notice by email to legal@seniorly.com or the address below</li>
    </ol>
    <p>
      Seniorly,
      P.O. Box 26804,
      San Francisco, California 94108.
      <br />
      Email Address:
      info@seniorly.com.
      <br />
      Telephone number:
      (415) 570-4370
    </p>
    <Heading level="subtitle">DISCLAIMER</Heading>
    <p>THE SITE AND THE SITE MATERIALS (INCLUDING ALL THIRD PARTY CONTENT), AND ALL LINKS, INFORMATION, MATERIALS, EVALUATIONS, RECOMMENDATIONS, SERVICES AND PRODUCTS PROVIDED ON OR THROUGH THE SITE ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. YOU EXPRESSLY AGREE THAT USE OF THE SITE AND THE MATERIALS IS AT YOUR SOLE RISK. SENIORLY AND ITS ASSOCIATED PARTIES (DEFINED AS AFFILIATES, SUCCESSORS, OFFICERS, DIRECTORS, SHAREHOLDERS, PERSONAL REPRESENTATIVES, AGENTS, AND EMPLOYEES) DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT AS TO THE SITE, THE SITE MATERIALS, LINKS, INFORMATION, MATERIALS, SERVICES AND PRODUCTS AVAILABLE ON OR THROUGH ON THE SITE AND/OR SERVICES. IN ADDITION, SENIORLY IS NOT RESPONSIBLE FOR THE PRODUCTS OR SERVICES PROVIDED BY, OR THE CONDUCT OF, ANY THIRD PARTY OR ITS AGENTS OR EMPLOYEES (EVEN IF WE HAVE INTRODUCED YOU TO SUCH PARTY OR PARTIES), INCLUDING WITHOUT LIMITATION, ANY PARTICIPATING COMMUNITY, PARTNER AGENT, OR OTHER HEALTH CARE AND/OR ANY OTHER SENIOR HOUSING AND CARE PROVIDER, WHETHER OFFLINE OR ONLINE. NO ORAL OR WRITTEN INFORMATION FROM SENIORLY OR ANY OTHER PARTY WILL MODIFY THIS DISCLAIMER. SENIORLY EXPRESSLY DISCLAIMS ANY REPRESENTATIONS, WARRANTIES OR COVENANTS THAT THE MATERIALS ON THE SITE ARE ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR-FREE. WHILE WE ATTEMPT TO PROVIDE YOU ACCESS SAFE FROM VIRUSES, SENIORLY DOES NOT REPRESENT, WARRANT OR COVENANT THAT THE SITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. IN NO EVENT SHALL SENIORLY BE LIABLE TO USER FOR ANY OF THE PRODUCTS, SERVICES, CONTENT OR INFORMATION PROVIDED THROUGH THE SITE OR OTHERWISE PROVIDED BY OR ON BEHALF OF SENIORLY.
      LIMITATION OF LIABILITY
    </p>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL SENIORLY OR THE ASSOCIATED PARTIES BE LIABLE FOR ANY DIRECT, SPECIAL, PUNITIVE, EXEMPLARY, INCIDENTAL, INDIRECT, CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND WHATSOEVER, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS, OR LOSS OF DATA OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, AND FOR ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE SITE AND/OR SERVICES, OUR ACTS OR OMMISSIONS UNDER OR IN ANY WAY RELATED TO THE SITE AND/OR SERVICES, OR OTHERWISE UNDER OR IN CONNECTION WITH THE SITE AND/OR SERVICES, REGARDLESS OF THE LEGAL THEORY INCLUDING WITHOUT LIMITATION TORT, STRICT LIABILITY, BREACH OF CONTRACT OR BREACH OF WARRANTY BY US OR ANY ASSOCIATED PARTY, AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATIONS, EXCLUSIONS AND DISCLAIMERS OF THIS "LIMITATION OF LIABILITY" SECTION SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CONSEQUENTIAL OR INDIRECT DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
    <Heading level="subtitle">INDEMNIFICATION</Heading>
    <p>You agree to indemnify and hold Seniorly and the Associated Parties harmless from any claim or demand, including attorneys' fees, arising out of your use of the Sites and/or the Services or your violation of our Terms of Use, or the infringement by you of any intellectual property or other right of any person or entity.</p>
    <Heading level="subtitle">TERMINATION</Heading>
    <p>We may terminate or suspend your access to the Sites at any time, with or without cause, and with or without notice. Upon such termination or suspension, your right to use the Sites will immediately cease.</p>
    <Heading level="subtitle">CHANGES TO THE SITES AND/OR SERVICES</Heading>
    <p>We reserve the right to change, modify, suspend, or cease providing the Sites and/or Services (and therefore, your access to and use of) at any time without notice.</p>
    <Heading level="subtitle">CHOICE OF LAW</Heading>
    <p>These Terms of Use are governed by the laws of the State of California, without giving effect to its conflict of laws provisions. You agree to submit to the personal and exclusive jurisdiction and venue in the state and federal courts sitting in San Francisco County, California for any and all disputes, claims and actions arising from or in connection with the Services and/or these Terms of Use. Seniorly operates the Services from its offices in California, and we make no representation that the Services are appropriate or available for use in other locations.</p>
    <Heading level="subtitle">CLAIMS SUBJECT TO MANDATORY AND BINDING ARBITRATION</Heading>
    <p>Subject to and without limiting the Governing Law section, you expressly agree that any claim or cause of action that arises from, relates to, or has connection with the Site and/or Services shall be adjudicated exclusively and finally by arbitration in California, administered by the American Health Lawyers Association Alternative Dispute Resolution Service under its Rules of Procedure for Arbitration (available at http://www.healthlawyers.org). The arbitration award shall be final and binding, and judgment on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. Except as required by applicable law, you knowingly, voluntarily, intelligently, and irrevocably waive any right to appeal from the arbitration award, including but not limited to any appeal from any judgment entered on the arbitration award or any order based thereupon. YOU EXPRESSLY AGREE THAT ANY CLAIM OR CAUSE OF ACTION THAT IS SUBJECT TO ARBITRATION UNDER THE TERMS OF USE MUST BE BROUGHT IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. YOU FURTHER EXPRESSLY AGREE THAT THE ARBITRATOR SHALL NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING. If a court decides that this “Mandatory and Binding Arbitration” subsection is not enforceable or is invalid, then this Section shall cease to have effect, however, the remaining portions of the Terms of Use will remain in full force and effect.</p>

    <Heading level="subtitle">GENERAL TERMS</Heading>
    <ol>
      <li >You agree not to export from anywhere any part of the Services provided to you, or any direct product thereof, except in compliance with, and with all licenses and approvals required under, applicable export laws, rules and regulations. All Services used by the U.S. Government are provided with the commercial license rights described herein. These Terms of Use may only be amended by a written agreement signed by authorized representatives of the parties to these Terms of Use. If any part of these Terms of Use is determined to be invalid or unenforceable, then the invalid or unenforceable provision will be replaced with a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms of Use will continue in effect. The section titles in these Terms of Use are solely used for the convenience of the parties and have no legal or contractual significance. Seniorly may assign this Agreement, in whole or in part, at any time with or without notice to you. You may not assign these Terms of Use, or assign, transfer or sublicense your rights, if any, in the Services. Seniorly's failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. Except as expressly stated herein, these Terms of Use, and all expressly incorporated terms and agreements, constitute the entire agreement between you and Seniorly with respect to the Services and supersede all prior or contemporaneous communications of any kind between you and Seniorly with respect to the Services.</li>
    </ol>
    <Heading>CONSENT TO COMMUNICATIONS</Heading>
    <p>By using the Services, you consent to receiving certain electronic communications from Seniorly as further described in the Privacy Policy. Please read the Privacy Policy to learn more. You agree that any notices, agreements, disclosures, or other communications that Seniorly sends to you electronically will satisfy any legal communication requirements, including that those communications be in writing.</p>
    <p>The Services may provide web forms, links, or contact information, including phone numbers, that can connect you with Seniorly or third parties, such as Partner Agents or Participating Communities. Communications through these methods may be routed through a third-party service ("Communications Service"). Calls may be recorded or monitored for quality assurance and customer service purposes. You will be notified at the beginning of a call if it may be recorded or monitored. You consent to such recording and monitoring by Seniorly or the Communications Service. Seniorly also uses the Communications Service to track phone calls and text messages between you and Partner Agents so that Seniorly and the Partner Agent can access certain details about the contact.  As part of this process, Seniorly and the Communications Service will receive in real time, and store, data about your call or text message, including the date and time of the call or text message, your phone number, and the content of the text message. You consent to these practices by Seniorly and the Communications Service. The information is subject to the Privacy Policy.</p>
    <Heading>CONTACT INFORMATION</Heading>
    <p>The Services are offered by Seniorly and its affiliates, located at 155 Montgomery Street, Suite 501, San Francisco, CA 94104. You may contact Seniorly by sending correspondence to that address or emailing legal@seniorly.com.</p>
    <p><br /><br /></p>

  </Block>);
};

export default TOSHTML;
