import React from 'react';

import { Heading, Block} from 'sly/components/atoms';


const TOSHTML = () => {
  return (<Block>
    <Heading level="subtitle">TERMS OF USE</Heading>
    <h3>EFFECTIVE AUGUST 2018</h3>
    <p>PLEASE READ THESE TERMS AND CONDITIONS OF USE ("TERMS OF USE") CAREFULLY. YOUR USE OF THIS WEB SITE AS WELL AS ALL OTHER WEB SITES OWNED AND/OR OPERATED BY SENIORLY (INDIVIDUALLY AND COLLECTIVELY, "SITE" OR "SITES")) AND/OR THE SERVICES PROVIDED BY SENIORLY THROUGH OR IN CONNECTION WITH THE SITES (INCLUDING SENIOR HOUSING AND CARE MARKETING AND INFORMATION SERVICES ("SERVICES")) IS CONDITIONED UPON YOUR ACCEPTANCE OF THESE TERMS OF USE WITHOUT MODIFICATION. BY ACCESSING OR USING THE SITES, YOU AGREE TO BE BOUND BY THE TERMS OF USE AND ALL TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO THE TERMS OF USE, DO NOT USE THE SITES AND/OR THE SERVICES.</p>
    <p>PLEASE NOTE THAT THESE TERMS OF USE CONTAIN CLASS ACTION WAIVER, WAIVER OF RIGHT TO JURY TRIAL, AND A MANDATORY AND BINDING ARBITRATION CLAUSE. THESE AFFECT YOUR RIGHTS ABOUT HOW TO RESOLVE ANY DISPUTE WITH SENIORLY. PLEASE READ IT.</p>
    <p>The Sites and the Services are provided by Seniorly, Inc. ("Seniorly").</p>
    <p>The Terms of Use apply to your access to, and use of, the Sites and/or the Services, so please read them carefully.</p>
    <p>We reserve the right to change or modify any of the Terms of Use, the Sites, and/or the Services at any time. If we decide to change our Terms of Use, we will post a new version on the Sites and update the date. Any changes or modifications will be effective immediately upon posting of the revisions on the Sites, regardless of whether we provide you with any specific notice of such changes or modifications. To the extent that notice is required under any applicable law or otherwise, you waive the right to such notice, provided that this sentence will not apply to you if you are a Washington State resident or to the extent you are seeking Services in Washington State. Your use of the Sites and/or the Services following the posting of changes or modifications to the Terms of Use will constitute your acceptance of the revised Terms of Use. Therefore, you should review the Terms of Use and applicable policies from time-to-time to understand the terms and conditions that apply to your use of the Sites and/or Services. If you do not agree to the amended terms, you must immediately stop using the Sites and/or Services.</p>
    <p>The Terms of Use do not alter in any way the terms or conditions of any other agreement you may have with Seniorly for services, products or otherwise. Your access to, and use of, the Sites may also be subject to any legal notices or additional terms and conditions applicable to the Sites and/or Services, in addition to these Terms of Use, ("Additional Terms"). Where Additional Terms apply to the Services, the Additional Terms will be accessible for you to read through your use of the Services and/or provided separately. These Terms of Use, together with the Additional Terms, form a legally binding agreement between you and Seniorly in relation to your use of the Sites and/or Services. It is important that you take the time to read them carefully. If there is any contradiction between what the Additional Terms say and what these Terms of Use say with respect to the Services, then the Additional Terms shall take precedence in relation to that Service.</p>
    <p>To use the Sites and/or Services, you must be of legal age to enter into a binding contract and not be prohibited from using the Sites and/or Services by the laws of the jurisdiction from which you access the Sites and/or Services.</p>
    <Heading level="subtitle">OUR SERVICES</Heading>
    <p>Seniorly is a senior housing and care marketing and information service that provides resources and personalized assistance in finding senior housing and care. We help families find options based on a loved one's stated needs and preferences and empower them to make informed decisions. This may include independent living, home care, residential care homes, assisted living, specialized memory care and skilled nursing. Based on the family's stated needs and preferences, we provide the family with information about contracted communities and local placement agents ("Participating Partners") and we forward the family's information to those Participating Partners. Families can review detailed information about local and national Participating Partners, and get personalized, knowledgeable assistance by telephone from a local Senior Living Advisor. The service is offered at no charge to families as the Participating Partners pay a fee to Seniorly.</p>
    <Heading level="subtitle">PARTICIPATING SENIOR HOUSING AND/OR CARE COMMUNITIES</Heading>
    <p>The Participating Partners are solely responsible for evaluating, accepting (or declining, as appropriate), and caring for all residents, including, without limitation, ensuring that their staff are appropriately qualified, current on education, and possess the necessary facilities, resources, and equipment to competently provide the services and care required by its residents. Each Participating Partner is responsible for the conditions at its community and the training of and acts and omissions of its employees, contractors, vendors, and any other individual who works at or for a community.</p>
    <p>Each Participating Partner is responsible for the content of the information posted on its page or on the Sites. The information does not represent our views or any individual associated with us, and we do not control this content. We do not vouch for the accuracy or completeness of any of the information posted by and/or for the Participating Partner on the Sites, and do not take any responsibility or assume any liability for any actions you may take as a result of reading the information posted by and/or for the Participating Partner on the Sites. By using the Sites and/or Services, you assume all associated risks.</p>
    <Heading level="subtitle">NO ENDORSEMENT; NO AFFILIATION; NOT A BROKER</Heading>
    <p>We exercise no independent judgment as to the quality of, nor do we recommend or endorse, any Participating Partner. We provide only an information service and do not (1) place the consumer in any Participating Partner, (2) perform any medical assessment of or for the consumer or the Participating Partner, or (3) participate in the consumer's and Participating Partner's decision regarding final selection or admittance. Further, we are not a representative of or agent for either the consumer or the Participating Partner and do not act on either's behalf. It is the responsibility solely of the Participating Partner and the potential resident, and/or the potential resident's family and care provider(s) and/or other involved parties acting on the potential resident's behalf to determine if any person is an appropriate admission to the Participating Partner. Seniorly does not broker, sell or lease space directly and is not a party to any transaction between the provider and the family.</p>
    <Heading level="subtitle">NO PROFESSIONAL ADVICE</Heading>
    <p>All information, materials, content and/or advice on the Sites or provided through the Services is for informational purposes only and is not intended to replace or substitute for any professional, financial, medical, legal or other advice. Seniorly expressly disclaims, and you expressly release Seniorly from, any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Sites and/or Services. You should consult with an appropriately trained specialist for all concerns that require medical, legal, financial or other professional advice.</p>
    <Heading level="subtitle">PRIVACY AND CONSENT TO COMMUNICATIONS</Heading>
    <p>Your privacy is important to us, and we provide a Privacy Policy that sets out how we collect and use your personal information collected from the Sites. Please review our Privacy Policy to which you should refer to fully understand how we collect and use personal information; your use of the Sites and/or Services will constitute your acceptance of the terms and conditions of the Privacy Policy. By filling out any forms on the Sites or providing information to us, you expressly consent to being contacted by us and/or the Participating Partners, whether by phone, mobile phone, email, mail or otherwise. If you are a customer or potential customer of the Services, you authorize us to provide the information that you provided us and related information we may receive from third parties to Participating Partners for the purpose of providing Services. Such authorization shall continue in effect until you have withdrawn your consent by requesting that we no longer provide you Services; provided that we may continue to refer to and/or disclose your information when communicating with a Participating Partner as necessary for our normal Participating Partner related business practices (such as Participating Partner billing matters) until such matters are closed.</p>
    <Heading level="subtitle">RECORDED TELEPHONE COMMUNICATIONS</Heading>
    <p>Telephone communications between You and Seniorly may be recorded or monitored for quality control purposes. By filling out any forms on the Sites or by providing information to us, you expressly consent to the recording of these telephone communications.</p>
    <Heading level="subtitle">USE OF SITES; LIMITED LICENSE</Heading>
    <p>You are granted a limited, non-sublicensable license to access and use the Sites and all content, data, information and materials included in the Sites (the "Site Materials") solely for your personal use, subject to the terms and conditions set forth in the Terms of Use. You will not use the Sites or any of the Site Materials other than for their intended purpose or in any way that is unlawful or harms Seniorly. Any use of the Sites or the Site Materials other than as specifically authorized herein is strictly prohibited and, without limiting other available remedies, will automatically and immediately terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in the Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable by Seniorly at any time.</p>
    <Heading level="subtitle">NO UNAUTHORIZED ACCESS OF AND/OR USE OF THE SITES AND/OR SERVICES</Heading>
    <p>The following are examples of some actions and activities that are prohibited by you in accessing and/or using the Sites and/or Services, and you agree not to do any of the following:</p>
    <ul>
      <li >Using the Sites for commercial purposes.</li>
      <li >Conducting or promoting any illegal activities while using the Sites or Services.</li>
      <li >Uploading or attempting to upload or otherwise transferring any virus, worm, trap door, back door, Trojan horse, timer, clock, counter, or other limiting or malicious routine, instruction, or design that would cause harm to the Sites, Seniorly's computer and/or telecommunication systems or data.</li>
      <li >Interfering in any way with the proper functioning of the Sites (including harming, disabling, or significantly slowing) or interfering with or disrupting any servers or networks connected to the Sites, or disobeying any requirements, procedures, policies or regulations of networks connected to the Sites.</li>
      <li >Modifying, copying, distributing, reselling, transmitting, displaying, performing, reproducing, publishing, licensing, creating derivative works from, framing in another web page, and/or using on any other Web site or service any of the Sites content.</li>
      <li >Engaging in the practices of "screen scraping," "database scraping," "data mining" or any other activity with the purpose of obtaining lists of users or other information, in whole or in part, from the Sites or use web "bots" or similar data gathering or extraction methods for such purposes.</li>
      <li >Attempting to reverse engineer or jeopardize the correct functioning of the Sites, or otherwise attempting to derive the source code of the software (including the tools, methods, processes, and infrastructure) that enables or underlies the Sites;</li>
      <li >Attempting to gain access to secured portions of the Sites.</li>
      <li >Circumventing, attempting to circumvent, disabling, or attempting to disable, or discovering or attempting to discover any security measures (including without limitation encryption algorithms, keys, passwords, and the like) used by or for Seniorly to protect its computer and/or telecommunications systems.</li>
      <li >Using the Sites and/or Services to generate unsolicited email advertisements or spam; and/or allowing, enabling, or otherwise supporting the transmission of mass unsolicited, commercial advertising or solicitations via e-mail (spam).</li>
      <li >Using the Sites and/or Services to stalk, harass or harm another individual.</li>
      <li >Impersonating any person or entity, or otherwise misrepresenting your affiliation with a person or entity; or</li>
      <li >Uploading, distributing or printing anything that may be harmful to minors.</li>
      <li >Mirroring or framing the Sites, placing pop-up windows over its pages, or otherwise affecting the display of its pages.</li>
      <li >Engaging in any other action in any way that is unlawful or harms Seniorly.</li>
    </ul>
    <Heading level="subtitle">INTELLECTUAL PROPERTY OWNERSHIP</Heading>
    <p>All trademarks, service marks, and trade names are proprietary to Seniorly and our licensors. All rights, title, and interests in and to the Sites, including content, materials, trademarks and other intellectual property contained in the Sites, vest solely in Seniorly and its licensors. The Seniorly name, and any Seniorly products and services, slogans or logos referenced herein on the Sites are either trademarks or registered trademarks of Seniorly in the United States and/or other countries. The names of actual third party companies and products mentioned in the Sites may be the trademarks of their respective owners. Any rights not expressly granted herein are reserved.</p>
    <Heading level="subtitle">ACCOUNT SECURITY</Heading>
    <p>On certain portions of the Sites, you will be provided with a password and user identification to use the Sites. You must agree to abide by these Site Terms and are responsible for all activity under such user identification. You are responsible for maintaining the confidentiality and security of any password connected with your account.</p>
    <Heading level="subtitle">HYPERLINKS TO EXTERNAL WEB SITES</Heading>
    <p>The Sites may provide links to external Web sites ("External Web Sites"). We provide these links to External Web Sites for your convenience only. We do not control such External Web Sites; therefore, Seniorly is not responsible for the content of any linked site or any link contained in a linked site. Our inclusion of links to such External Web Sites does not imply any endorsement of any such third party who advertises their goods or services through the Sites (including Participating Partners). We make no claim or representation regarding, and accept no responsibility for, the quality, content, nature or reliability of External Web Sites.</p>
    <p>When you leave the Site, you should be aware that our Terms of Use and our Privacy Policy do not apply to your use of External Web Sites. You should review the applicable terms and policies, including privacy and data gathering practices, of any External Web Sites to which you navigate from the Site. Your use of and dealings with the owners or operators of these External Web Sites are at your own risk, and you agree not to make any claim against Seniorly arising out of your use of these External Web Sites.</p>
    <Heading level="subtitle">THIRD PARTY PRODUCTS AND SERVICES</Heading>
    <p>We may run advertisements and promotions from third parties (including Participating Partners) on the Sites or may otherwise provide information about or links or referrals to third-party (including Participating Partners) products or services on the Sites ("Third Party Products and Services").</p>
    <p>We do not make any guarantees about the accuracy, currency, suitability, or quality of the information about such Third Party Products and Services, and we assume no responsibility for unintended, objectionable, inaccurate, misleading, or unlawful content made available by Third Party Products and Services. Because we do not control such Third Party Products and Services, we are not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or promotions or from any Third Party Products and Services, and you use such Third Party Products and Services at your own risk.</p>
    <p>Your business dealings or correspondence with, or participation in promotions of, such Third Party Products and Services, and any terms, conditions, warranties or representations associated with such dealings or promotions are solely between you and such third party.</p>
    <p>You should investigate and use your independent judgment regarding the merits, quality and reputation of any Third Party Products and Services that you find on or through the Sites.</p>
    <Heading level="subtitle">PUBLIC AREAS AND SUBMISSIONS</Heading>
    <p>If you use a "Public Area", such as the Help Center, message boards, or other community area that allows user posts, additional terms and conditions apply to you.</p>
    <p>You agree that any materials, including but not limited to questions, comments, suggestions, ideas, plans, notes, drawings, original or creative materials or other information regarding Seniorly, the Sites, and/or the Services, provided by you in any manner including but not limited to e-mail, other written, or oral submissions to Seniorly, or postings on the Sites ("Submissions"), are non-confidential. We are entitled to the unrestricted use, dissemination, distribution, display, reproduction, sublicense, post, and/or publication of the Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you, and we will own the exclusive rights, including all intellectual property rights, to the Submissions.</p>
    <p>If you are an author of a Submission, you warrant that you will not post any materials that would (a) constitute or encourage conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any local, state, national or international law, including any threatening, libelous, defamatory, obscene, vulgar, pornographic, profane or indecent messages of any kind; (b) violate or infringe upon the rights of others, including their privacy or publicity rights, or which is protected by copyright, trademark or other proprietary rights, without first obtaining permission from the person who owns or holds that right; (c) contain a virus or other material of a destructive nature; and (d) violate any law, statute, ordinance or regulation including but not limited to misrepresentation, fraud, deception, anti-discrimination, and/or false advertising.</p>
    <p>Additional terms and conditions may apply to you in your use of the "Public Area", the Eldercare Forum, message board, or other community area.</p>
    <Heading level="subtitle">DISCLAIMER</Heading>
    <p>THE SITES AND THE SITE MATERIALS (INCLUDING ALL THIRD PARTY CONTENT), AND ALL LINKS, INFORMATION, MATERIALS, EVALUATIONS, RECOMMENDATIONS, SERVICES AND PRODUCTS PROVIDED ON OR THROUGH THE SITES ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. YOU EXPRESSLY AGREE THAT USE OF THE SITES AND THE MATERIALS IS AT YOUR SOLE RISK. SENIORLY AND ITS ASSOCIATED PARTIES (DEFINED AS AFFILIATES, SUCCESSORS, OFFICERS, DIRECTORS, SHAREHOLDERS, PERSONAL REPRESENTATIVES, AGENTS, AND EMPLOYEES) DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT AS TO THE SITES, THE SITE MATERIALS, LINKS, INFORMATION, MATERIALS, SERVICES AND PRODUCTS AVAILABLE ON OR THROUGH ON THE SITES AND/OR SERVICES. IN ADDITION, SENIORLY IS NOT RESPONSIBLE FOR THE PRODUCTS OR SERVICES PROVIDED BY, OR THE CONDUCT OF, ANY THIRD PARTY OR ITS AGENTS OR EMPLOYEES (EVEN IF WE HAVE INTRODUCED YOU TO SUCH PARTY OR PARTIES), INCLUDING WITHOUT LIMITATION, ANY PARTICIPATING PARTNER OR OTHER HEALTH CARE AND/OR ANY OTHER SENIOR HOUSING AND CARE PROVIDER, WHETHER OFFLINE OR ONLINE. NO ORAL OR WRITTEN INFORMATION FROM SENIORLY OR ANY OTHER PARTY WILL MODIFY THIS DISCLAIMER. SENIORLY EXPRESSLY DISCLAIMS ANY REPRESENTATIONS, WARRANTIES OR COVENANTS THAT THE MATERIALS ON THE SITES ARE ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR-FREE. WHILE WE ATTEMPT TO PROVIDE YOU ACCESS SAFE FROM VIRUSES, SENIORLY DOES NOT REPRESENT, WARRANT OR COVENANT THAT THE SITES OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. IN NO EVENT SHALL SENIORLY BE LIABLE TO USER FOR ANY OF THE PRODUCTS, SERVICES, CONTENT OR INFORMATION PROVIDED THROUGH THE SITES OR OTHERWISE PROVIDED BY OR ON BEHALF OF SENIORLY.</p>
    <Heading level="subtitle">LIMITATION OF LIABILITY</Heading>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL SENIORLY OR THE ASSOCIATED PARTIES BE LIABLE FOR ANY DIRECT, SPECIAL, PUNITIVE, EXEMPLARY, INCIDENTAL, INDIRECT, CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND WHATSOEVER, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS, OR LOSS OF DATA OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, AND FOR ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE SITES AND/OR SERVICES, OUR ACTS OR OMMISSIONS UNDER OR IN ANY WAY RELATED TO THE SITES AND/OR SERVICES, OR OTHERWISE UNDER OR IN CONNECTION WITH THE SITES AND/OR SERVICES, REGARDLESS OF THE LEGAL THEORY INCLUDING WITHOUT LIMITATION TORT, STRICT LIABILITY, BREACH OF CONTRACT OR BREACH OF WARRANTY BY US OR ANY ASSOCIATED PARTY, AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATIONS, EXCLUSIONS AND DISCLAIMERS OF THIS "LIMITATION OF LIABILITY" SECTION SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS (SUCH AS WASHINGTON STATE) DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CONSEQUENTIAL OR INDIRECT DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
    <Heading level="subtitle">INDEMNIFICATION</Heading>
    <p>You agree to indemnify and hold Seniorly and the Associated Parties harmless from any claim or demand, including attorneys' fees, arising out of your use of the Sites and/or the Services or your violation of our Terms of Use, or the infringement by you of any intellectual property or other right of any person or entity.</p>
    <Heading level="subtitle">TERMINATION</Heading>
    <p>We may terminate or suspend your access to the Sites at any time, with or without cause, and with or without notice. Upon such termination or suspension, your right to use the Sites will immediately cease.</p>
    <Heading level="subtitle">CHANGES TO THE SITES AND/OR SERVICES</Heading>
    <p>We reserve the right to change, modify, suspend, or cease providing the Sites and/or Services (and therefore, your access to and use of) at any time without notice.</p>
    <Heading level="subtitle">GOVERNING LAW AND FORUM SELECTION</Heading>
    <p>The Terms of Use are construed under the laws of the State of California, without reference to its conflict of laws provisions. You agree that any action at law or in equity arising out of or relating to the Sites and/or Services can be filed only and exclusively in a state or federal court located in San Francisco, California, and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction and venue of such courts over any suit, action or proceeding arising out of the Sites and/or Services. You hereby knowingly, voluntarily, intelligently, and irrevocably waive any available affirmative defenses under federal law or any states' laws to venue and jurisdiction in San Francisco, California, including without limitation improper venue, forum non conveniens, lack of in personam jurisdiction, and all related defenses. You further agree that this forum-selection clause shall apply to any and all claims under federal law or any states' laws and that arise from or relate in any way to the Sites and/or Services, including, without limitation, contract, tort, and all other statutory or common law claims seeking equitable or legal relief, whether asserted as a cause of action, counterclaim, cross-claim, affirmative defense, or otherwise, and whether asserted on an individual basis or as putative representative of a class.</p>
    <Heading level="subtitle">CLASS ACTION WAIVER</Heading>
    <p>For disputes arising between Seniorly and you, or any other user, you and we agree that we can only bring a claim against each other on an individual basis. NEITHER YOU NOR WE CAN BRING A CLAIM AS A PLAINTIFF OR CLASS MEMBER IN A CLASS ACTION, CONSOLIDATED ACTION, OR REPRESENTATIVE ACTION. If a court decides that this &ldquo;Class Action Waiver&rdquo; subsection is not enforceable or is invalid, then this Section shall cease to have effect, however, the remaining portions of the Terms of Use will remain in full force and effect.</p>
    <Heading level="subtitle">WAIVER OF RIGHT TO JURY TRIAL</Heading>
    <p>YOU HEREBY KNOWINGLY, VOLUNTARILY, INTELLIGENTLY, AND IRREVOCABLY WAIVE YOUR RIGHTS TO A JURY TRIAL OF ANY CLAIM OR CAUSE OF ACTION BASED UPON, ARISING OUT OF, OR IN ANY MANNER RELATING TO THE TERMS OF USE AND/OR SENIORLY'S PERFORMANCE OR FAILURE TO PERFORM HEREUNDER. The scope of this waiver is intended to be all-encompassing and shall apply to any and all claims arising under federal law or any states' laws and that arise from or relate in any way to the subject matter of the Terms of Use and/or our performance, including, without limitation, contract, tort, and all other statutory or common law claims seeking equitable or legal relief, whether asserted as a cause of action, counterclaim, cross-claim, affirmative defense, or otherwise, and whether asserted on an individual basis or as putative representative of a class. You expressly acknowledge that this provision is an essential aspect of the bargain embodied by the Terms of Use. If a court decides that this &ldquo;Waiver of Right to Jury Trial&rdquo; subsection is not enforceable or is invalid, then this Section shall cease to have effect, however, the remaining portions of the Terms of Use will remain in full force and effect.</p>
    <Heading level="subtitle">CLAIMS SUBJECT TO MANDATORY AND BINDING ARBITRATION</Heading>
    <p>Subject to and without limiting the Governing Law and Forum Selection section, you expressly agree that any claim or cause of action that arises from, relates to, or has connection with the Sites and/or Services shall be adjudicated exclusively and finally by arbitration in California, administered by the American Health Lawyers Association Alternative Dispute Resolution Service under its Rules of Procedure for Arbitration (available at http://www.healthlawyers.org). The arbitration award shall be final and binding, and judgment on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. Except as required by applicable law, you knowingly, voluntarily, intelligently, and irrevocably waive any right to appeal from the arbitration award, including but not limited to any appeal from any judgment entered on the arbitration award or any order based thereupon. YOU EXPRESSLY AGREE THAT ANY CLAIM OR CAUSE OF ACTION THAT IS SUBJECT TO ARBITRATION UNDER THE TERMS OF USE MUST BE BROUGHT IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. YOU FURTHER EXPRESSLY AGREE THAT THE ARBITRATOR SHALL NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING. If a court decides that this &ldquo;Mandatory and Binding Arbitration&rdquo; subsection is not enforceable or is invalid, then this Section shall cease to have effect, however, the remaining portions of the Terms of Use will remain in full force and effect.</p>
    <Heading level="subtitle">WAIVERS NOT APPLICABLE IN WASHINGTON STATE</Heading>
    <p>To the extent such provisions are not allowed or we otherwise state in writing to you that such provisions of the Terms of Use are not intended by us to apply to you, waivers of liability and rights by certain individuals do not apply under Washington State law and therefore the waivers of liability and rights set out in the Terms of Use may not apply to you if you are a Washington State resident or to the extent you are seeking Services in Washington State.</p>
    <Heading level="subtitle">COPYRIGHT INFRINGEMENT NOTICES &amp; DMCA NOTICES</Heading>
    <p>If you believe in good faith that materials hosted by us infringe your copyright, you (or your agent) may send us a written notice that includes the following information. Please note that we will not process your complaint if it is not properly filled out or is incomplete. Any misrepresentations in your notice whether content or activity is infringing may expose you to liability for damages.</p>
    <ol>
      <li >A clear identification of the copyrighted work you claim was infringed</li>
      <li >A clear identification of the material you claim is infringing on the Website, such as a link to the infringing material.</li>
      <li >Your address, email address and telephone number.</li>
      <li >A statement that you have a ''good faith belief that the material that is claimed as copyright infringement is not authorized by the copyright owner, its agent, or the law.''</li>
      <li >A statement that ''the information in the notification is accurate, and under penalty of perjury, the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed''</li>
      <li >A signature by the person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
      <li >You may send your notice by email to legal@seniorly.com or the address below</li>
    </ol>
    <p>
      Seniorly,
      155 Montgomery St, Suite 501
      San Francisco, California 94108.
      <br/>
      Email Address:
      info@seniorly.com.
      <br/>
      Telephone number:
      (415) 570-4370
    </p>
    <Heading level="subtitle">GENERAL TERMS</Heading>
    <ol>
      <li >If any part of the Terms of Use is determined to be invalid or unenforceable pursuant to applicable law, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use will continue in effect. You may not assign the Terms of Use, or assign, transfer or sublicense your rights, if any, in the Sites. Except as expressly stated herein, the Terms of Use constitute the entire agreement between you and Seniorly with respect to the Sites.</li>
    </ol>
    <p><br /><br /></p>
  </Block>);

};

export default TOSHTML;
