# Do not include user specific config like global.profile
# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-profile
# https://github.com/aws-samples/eb-python-flask/blob/master/.elasticbeanstalk/config.global.yml
branch-defaults:
  default:
    environment: slyreact-development
  master:
    environment: slyreact-development
environment-defaults:
  slyreact-development:
    branch: null
    repository: null
  slyreact-staging:
    branch: null
    repository: null
global:
  application_name: SlyReact
  default_ec2_keyname: slynode-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  sc: git
  workspace_type: Application
