# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies

      - run: npm install

      - run:
          name: Setup dirs
          command: mkdir -p $TEST_RESULTS

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
#     - run:
#         name: "JavaScript Linter"
#         command: yarn lint -- --format junit -o "$TEST_RESULTS/js-lint-results.xml"
      # run tests!
      - run:
          name: "JS Test Suite"
          command: JEST_JUNIT_OUTPUT="$TEST_RESULTS/junit/js-test-results.xml" npm test -- --ci --testResultsProcessor="jest-junit"

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
