export const CONVERSATION_PARTICIPANT_TYPE_USER = 'User';

export const CONVERSATION_PARTICIPANT_TYPE_CLIENT = 'Client';

export const CONVERSATION_PARTICIPANT_TYPE_ORGANIZATION = 'Organization';

export const CONVERSATION_STATUS_LIVE = 'Live';

export const CONVERSATION_STATUS_ARCHIVED = 'Archived';

export const CONVERSATION_MEDIUM_INAPP = 'InApp';

export const CONVERSATION_MEDIUM_SMS = 'Sms';

export const CONVERSATION_MEDIUM_EMAIL = 'Email';

export const CONVERSATION_MESSAGE_DATA_TYPE_TEXT = 'Text';

export const CONVERSATION_MESSAGE_DATA_TYPE_BUTTONLIST = 'ButtonList';

export const CONVERSATION_MESSAGE_DATA_TYPE_BUTTONLIST_ACTION_AUTOMATED_RESPONSE = 'AutomatedResponse';

export const CONVERSATION_MESSAGE_DATA_TYPE_BUTTONLIST_ACTION_OPEN_LINK = 'OpenLink';

export const MESSAGES_UPDATE_LAST_READ_TIMEOUT = 10000;
