export const DASHBOARD_PATH = '/dashboard';

const FAMILY_DASHBOARD_PATH = `${DASHBOARD_PATH}/family`;
const AGENT_DASHBOARD_PATH = `${DASHBOARD_PATH}/agent`;

export const FAMILY_DASHBOARD_FAVORITES_PATH = `${FAMILY_DASHBOARD_PATH}/favorites`;
export const FAMILY_DASHBOARD_PROFILE_PATH = `${FAMILY_DASHBOARD_PATH}/my-profile`;
export const FAMILY_DASHBOARD_FAMILIES_PATH = `${AGENT_DASHBOARD_PATH}/my-families`;
export const FAMILY_DASHBOARD_FAMILIES_DETAILS_PATH = `${AGENT_DASHBOARD_PATH}/my-families/:id`;
export const FAMILY_DASHBOARD_FAMILIES_DETAILS_TAB_PATH = `${FAMILY_DASHBOARD_FAMILIES_DETAILS_PATH}/:tab`;
