export default {
  CA: ['Assisted Living', 'Memory Care', 'Independent Living', 'Enhanced Assisted Living'],
  TX: ['Assisted Living', 'Memory Care', 'Independent Living'],
  FL: ['Assisted Living'],
  NY: ['Adult Homes', 'Adult Care Facilities', 'Assisted Living', 'Memory Care', 'Alzheimer Care', 'Enhanced Assisted Living'],
  PA: ['Memory Care', 'Independent Living', 'Respite Care', 'Personal Care Home'],
  IL: ['Assisted Living', 'Supportive Living'],
  OH: ['Nursing Homes'],
  GA: ['Skilled Nursing', 'Independent Living', 'Personal Care Home'],
  NC: ['Independent Living', 'Skilled Nursing', 'Assisted Living'],
  MI: ['Assisted Living', 'Adult Foster Care', 'Retirement Community', 'Nursing Homes'], // check
  NJ: ['Assisted Living', 'Nursing Home', 'Retirement Communities', 'Skilled Nursing'],
  VA: ['Nursing Homes', 'Residential Care Homes', 'Assisted Living'],
  WA: ['Assisted Living', 'Independent Living', 'Memory Care', 'Enhanced Assisted Living'],
  AZ: ['Residential Care Homes', 'Assisted Living', 'Respite Care', 'Adult Day Care'],
  MA: ['Assisted Living', 'Adult Foster Care'],
  TN: ['Nursing Homes', 'Assisted Living', 'Residential Homes for the Aged'],
  IN: ['Assisted Living', 'Residential Care Facility', 'Adult Foster Care'],
  MO: ['Assisted Living', 'Residential Care facilities', 'Intermediate Care Facilities', 'Skilled Nursing Facilities', 'Nursing Home', 'Long Term Care'],
  MD: ['Nursing Home', 'Assisted Living', 'Home Care', 'Adult Day Care', 'Adult Foster Care'],
  WI: ['Adult Family Home', 'Residential Care', 'Nursing Homes'],
  CO: ['Nursing Homes', 'Assisted Living', 'Home Care'],
  MN: ['Assisted Living', 'Independent Living', 'Nursing Homes', 'Retirement Community'],
  SC: ['Retirement Community', 'Nursing Home', 'Assisted Living'],
  AL: ['Assisted Living', 'Continuing Care Retirement Community(CCRC)', 'Nursing Care', 'Memory Care'],
  LA: ['Assisted Living', 'Retirement Homes', 'Nursing Homes'],
  KY: ['Adult Foster Care', 'Residential Care', 'Assisted Living', 'Nursing Facility', 'Personal Care home'],
  OR: ['Personal Care', 'Nursing Facility', 'Residential Care', 'Adult Foster Home'],
  OK: ['Personal Care', 'Assisted Living', 'Independent Living', 'Respite Care', 'Memory Care'],
  CT: ['Assisted Living', 'Adult Foster Care', 'Independent Living', 'Nursing Home', 'Retirement Community'],
  IA: ['Assisted Living', 'Residential Care Facility', 'Nursing Homes', 'Elder Group Home'],
  UT: ['Assisted Living', 'Nursing Homes', 'Skilled Nursing', 'Hospice'],
  AR: ['Assisted Living', 'Nursing Homes'],
  NV: ['Assisted Living', 'Personal Care (Medicaid)'],
  MS: ['Assisted Living', 'Personal Care Home', 'Skilled Nursing'],
  KS: ['Nursing Homes', 'Assisted Living'],
  NM: ['Independent Living', 'Assisted Living', 'Skilled Nursing', 'Respite Care'],
  NE: ['Assisted Living', 'Adult Day Care', 'Respite Care', 'Home Care', 'Skilled Nursing'],
  WV: ['Assisted Living', 'Respite Care', 'Nursing Home', 'Independent Living', 'Retirement Community', 'Adult Foster Care'],
  ID: ['Nursing Homes', 'Residential Care', 'Assisted Living', 'Retirement Communities'],
  HI: ['Assisted Living', 'Intermediate Care Facilities', 'Skilled Nursing'],
  NH: ['Assisted Living', 'Adult Day Care', 'Home Care', 'Skilled Nursing'],
  ME: ['Adult Day Care', 'Home Care', 'Long term Care Facilities', 'Respite Care'],
  RI: ['Assisted Living', 'Home Care', 'Adult Day Care', 'Memory Care'],
  MT: ['Adult Residential Living(Adults with Disabilities)', 'Assisted Living'],
  DE: ['Assisted Living', 'Long Term Care Facilities', 'Adult Foster Care', 'Nursing Homes'],
  SD: ['Nursing Homes', 'Assisted Living', 'Retirement Community', 'Adult Day Care', 'Home Care', 'Adult Foster Care'],
  ND: ['Assisted Living', 'Basic Care Facility', 'Adult Foster Care', 'Skilled Nursing', 'Adult Day Care'],
  AK: ['Supportive Living', 'Assisted Living', 'Residential Care', 'Adult Foster Care'],
  DC: ['Assisted Living', 'Long Term Care'],
  VT: ['Nursing Home', 'Assisted Living', 'Residential Care Home'],
  WY: ['Assisted Living', 'Adult Day Care', 'Adult Foster Homes', 'Boarding Home', 'Intermediate Care Homes', 'Nursing Care Homes'],
};
