export const TASK_STATUS_DELETED = -10;
export const TASK_STATUS_INITED = 0;
export const TASK_STATUS_IN_PROGRESS = 10;
export const TASK_STATUS_COMPLETED = 20;

export const TASK_PRIORITY_LOW = 0;
export const TASK_PRIORITY_MED = 1;
export const TASK_PRIORITY_HIGH = 2;

export const TASK_PRIORITY_LABEL_MAP = {};
TASK_PRIORITY_LABEL_MAP[TASK_PRIORITY_LOW] = 'Low';
TASK_PRIORITY_LABEL_MAP[TASK_PRIORITY_MED] = 'Medium';
TASK_PRIORITY_LABEL_MAP[TASK_PRIORITY_HIGH] = 'High';

export const TASK_STATUS_LABEL_MAP = {};
TASK_STATUS_LABEL_MAP[TASK_STATUS_DELETED] = 'Deleted';
TASK_STATUS_LABEL_MAP[TASK_STATUS_INITED] = 'Not Started';
TASK_STATUS_LABEL_MAP[TASK_STATUS_IN_PROGRESS] = 'In Progress';
TASK_STATUS_LABEL_MAP[TASK_STATUS_COMPLETED] = 'Completed';

export const TASK_TOTAL_STAGES = 3;

export const TASK_STATUS_ORDERED = [TASK_STATUS_INITED, TASK_STATUS_IN_PROGRESS, TASK_STATUS_COMPLETED];
