export const COMMUNITY_SEARCH_TOGGLE_MODAL_FILTER_PANEL = 'COMMUNITY_SEARCH_TOGGLE_MODAL_FILTER_PANEL';

export const toggleModalFilterPanel = () => ({
  type: COMMUNITY_SEARCH_TOGGLE_MODAL_FILTER_PANEL,
});
