export const fieldNames = {
  name: 'Community name',
  'propInfo.communityPhone': 'Front desk phone number',
  'propInfo.ownerName': 'Owner name',
  'propInfo.ownerEmail': 'Owner email',
  'propInfo.websiteUrl': 'Website Url',
  'propInfo.parentCompany': 'Parent Company',
  'propInfo.communitySize': 'Community Size',
  'propInfo.capacity': 'Licensed Capacity',
  'propInfo.typeCare': 'Care type',
  'propInfo.respiteAllowed.checked': 'Respite care allowed',
  'propInfo.respiteAllowed.minlength': 'Minimum stay length',
  'propInfo.licenseNumber': 'License number',
  'address.line1': 'Address line 1',
  'address.line2': 'Address line 2',
  'address.city': 'Address city',
  'address.state': 'Address state',
  'address.zip': 'Address zip',
  'propInfo.careServices': 'Care Services',
  'propInfo.nonCareServices': 'Services',
  'propInfo.nonCareServicesOther': 'Services',
  'propInfo.sharedSuiteRate': 'Shared suite rate',
  'propInfo.privateSuiteRate': 'Pricing',
  'propInfo.studioApartmentRate': 'Pricing',
  'propInfo.oneBedroomApartmentRate': 'Pricing',
  'propInfo.twoBedroomApartmentRate': 'Pricing',
  'propInfo.isCareCostIncluded': 'Pricing',
  'propInfo.alCareRate': 'Pricing',
  'propInfo.mcCareRate': 'Pricing',
  'propInfo.isUtilitiesIncluded': 'Pricing',
  'propInfo.communitySpace': 'Amenities',
  'propInfo.communitySpaceOther': 'Amenities',
  'propInfo.communityDescription': 'Community Description',
  'rgsAux.rgsInfo.contract_info.hasContract': 'Contract',
  'rgsAux.rgsInfo.contract_info.contractType': 'Contract',
  'rgsAux.rgsInfo.contract_info.value': 'Contract',
  'rgsAux.rgsInfo.contract_info.notes': 'Contract',
  'gallery.images': 'Photos',
  'propInfo.covidInfoTitle': 'Covid Title',
  'propInfo.covidInfoDescription': 'Covid Description',
  'propInfo.promoTitle': 'Promotion Title',
  'propInfo.promoDescription': 'Promotion Description',
  'propInfo.adminNotes': 'Notes',
  'slyScore': 'Sly Score',
  'status': 'Status',
  'propInfo.websiteTitle': 'Title Tag',
  'propInfo.websiteMetaDescription': 'Meta Description',

};

export const sectionMap = {
  name: 'Profile',
  'propInfo.communityPhone': 'Profile',
  'propInfo.ownerName': 'Profile',
  'propInfo.ownerEmail': 'Profile',
  'propInfo.typeCare': 'Profile',
  'propInfo.respiteAllowed.checked': 'Profile',
  'propInfo.respiteAllowed.minlength': 'Profile',
  'propInfo.licenseNumber': 'Profile',
  'propInfo.websiteUrl': 'Profile',
  'propInfo.parentCompany': 'Profile',
  'propInfo.communitySize': 'Profile',
  'propInfo.capacity': 'Profile',
  'address.line1': 'Profile',
  'address.line2': 'Profile',
  'address.city': 'Profile',
  'address.state': 'Profile',
  'address.zip': 'Profile',
  'propInfo.careServices': 'Care services',
  'propInfo.nonCareServices': 'Community services',
  'propInfo.nonCareServicesOther': 'More about the community services',
  'propInfo.sharedSuiteRate': 'Shared suite rate',
  'propInfo.privateSuiteRate': 'Private suite rate',
  'propInfo.studioApartmentRate': 'Studio apartment rate',
  'propInfo.oneBedroomApartmentRate': 'One bedroom apartment rate',
  'propInfo.twoBedroomApartmentRate': 'Two bedroom apartment rate',
  'propInfo.isCareCostIncluded': 'Care costs included',
  'propInfo.alCareRate': 'Assisted living cost included',
  'propInfo.mcCareRate': 'Memory care cost included',
  'propInfo.isUtilitiesIncluded': 'Utilities cost included',
  'propInfo.communitySpace': 'Amenities',
  'propInfo.communitySpaceOther': 'Other amenities',
  'propInfo.communityDescription': 'Community Description',
  'rgsAux.rgsInfo.contract_info.hasContract': 'Has contract',
  'rgsAux.rgsInfo.contract_info.contractType': 'Contract type',
  'rgsAux.rgsInfo.contract_info.value': 'Contract value',
  'rgsAux.rgsInfo.contract_info.notes': 'Contract notes',
  'gallery.images': 'Photos',
  'propInfo.covidInfoTitle': 'Admin',
  'propInfo.covidInfoDescription': 'Admin',
  'propInfo.promoTitle': 'Admin',
  'propInfo.promoDescription': 'Admin',
  'propInfo.adminNotes': 'Admin',
  'slyScore': 'Admin',
  'status': 'Admin',
  'propInfo.websiteTitle': 'Admin',
  'propInfo.websiteMetaDescription': 'Admin',
};

export const blacklist = [
  'lastViewedAt',
  'createdAt',
  'updatedAt',
  'user.uuid',
];
