export const REQUEST_CALLBACK = 'LEAD/REQUEST_CALLBACK';
export const REQUEST_PRICING = 'LEAD/REQUEST_PRICING';
export const REQUEST_AVAILABILITY = 'LEAD/REQUEST_AVAILABILITY';
export const REQUEST_CONSULTATION = 'LEAD/REQUEST_CONSULTATION';
export const ASSESSMENT = 'LEAD/ASSESSMENT';
export const CAW_PROGRESS = 'LEAD/CAW_PROGRESS';
