export const cmsHubTypes = [
  'nursing-homes',
  'assisted-living',
  'independent-living',
  'board-and-care-home',
  'memory-care',
  'continuing-care-retirement-community',
  'skilled-nursing-facility',
  'senior-living',
  'in-home-care',
  'respite-care',
  'veterans-benefit-assisted-living',
  'active-adult',
  'what-is-medicare',
  'what-is-medicaid',
  'what-are-activities-of-daily-living-adls',
];
