export default [
  'nursing-homes',
  'assisted-living',
  'independent-living',
  'board-and-care-home',
  'memory-care',
  'continuing-care-retirement-community',
  'skilled-nursing-facility',
  'senior-living',
  'in-home-care',
  'respite-care',
  'veterans-benefit-assisted-living',
  'active-adult',
];

export const cmsHubTypes = [
  'nursing-homes-temp',
  'assisted-living-temp',
  'independent-living-temp',
  'board-and-care-home-temp',
  'memory-care-temp',
  'continuing-care-retirement-community-temp',
  'skilled-nursing-facility-temp',
  'senior-living-temp',
  'in-home-care-temp',
  'respite-care-temp',
  'veterans-benefit-assisted-living-temp',
  'active-adult-temp',
  'what-is-medicare',
  'what-is-medicaid',
  'what-is-adl-s',
];
