export const TASK_STATUS_DELETED = 'Deleted';
export const TASK_STATUS_NOT_STARTED = 'Not Started';
export const TASK_STATUS_IN_PROGRESS = 'In Progress';
export const TASK_STATUS_COMPLETED = 'Completed';

export const TASK_PRIORITY_LOW = 'Low';
export const TASK_PRIORITY_MED = 'Medium';
export const TASK_PRIORITY_HIGH = 'High';
export const TASK_PRIORITY_URGENT = 'Urgent';

export const TASK_TOTAL_STAGES = 3;

export const TASK_STATUS_ORDERED = [TASK_STATUS_NOT_STARTED, TASK_STATUS_IN_PROGRESS, TASK_STATUS_COMPLETED];

export const TASK_PRIORITIES_ORDERED = [TASK_PRIORITY_LOW, TASK_PRIORITY_MED, TASK_PRIORITY_HIGH, TASK_PRIORITY_URGENT];

export const TASK_STATUS_NOT_STARTED_CODE = 0;
export const TASK_STATUS_IN_PROGRESS_CODE = 10;
export const TASK_STATUS_COMPLETED_CODE = 20;

export const TASK_RELATED_ENTITY_TYPE = 'SlyEntity';
